### ISSUE TITLE
Instagram feed widget

### ISSUE THREAD

**Issue by Antholimere** [AnaYs/latitudes#14]
We could use https://lightwidget.com for the feed. I tried it, it's easy to implement and pretty straight-forward.

This is code to call it in the view
`<!-- LightWidget WIDGET --><script src="//lightwidget.com/widgets/lightwidget.js"></script><iframe src="//lightwidget.com/widgets/f3321f0aae8e515496d3ef8e70852ad6.html" id="lightwidget_f3321f0aae" name="lightwidget_f3321f0aae"  scrolling="no" allowtransparency="true" class="lightwidget-widget" style="width: 100%; border: 0; overflow: hidden;"></iframe>`

Last step is for you to authorize it https://lightwidget.com/auth/

**Comment by AnaYs** [comment]
`<!-- LightWidget WIDGET --><script src="//lightwidget.com/widgets/lightwidget.js"></script><iframe src="//lightwidget.com/widgets/ab705cbad48b5ce2856d3510d4fae65e.html" id="lightwidget_ab705cbad4" name="lightwidget_ab705cbad4"  scrolling="no" allowtransparency="true" class="lightwidget-widget" style="width: 100%; border: 0; overflow: hidden;"></iframe>`
